name: 👷 Contribute to next priorities
description: Help us with our work on our next priorities 
title: 'contribution: '
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our project!"
  - type: markdown
    attributes:
      value: |
        - Before we start developing these components or patterns, we want to ensure that the GC community has an opportunity to submit contributions that can accelerate and inform design and delivery.
        - The types of contributions we'll be looking for:
          - **examples of designs**: screenshots, prototypes, links to live services
          - **research findings**: tell or show us your discovery, your use case, or how your relevant prototype or service has been tested with people using the service
          - **code**: prototype code or production code; share your implementations of the relevant component or pattern in services
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Complete all of the following.
      options:
        - label: I've read the [Contributing Guidelines](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: dropdown
    id: contribution-type
    attributes:
      label: Which component or pattern is this contribution for?
      options:
        - Data Table
        - Image
        - Tags
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your contribution.
      description: Attach screenshots, or a detailed description of your contribution.
    validations:
      required: true
