name: 👷 Contribute to next priorities
description: Help us with our work on our next priorities 
title: 'contribution: '
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Complete all of the following.
      options:
        - label: I've read the [Contributing Guidelines](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: dropdown
    id: contribution-type
    attributes:
      label: Which component or pattern is this contribution for?
      options:
        - Data Table
        - Card (v2)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your contribution.
      description: Attach screenshots, or a detailed description of your contribution.
    validations:
      required: true
