name: 💡 Feature Request
description: Suggest an idea for GC Design System Components
title: 'feat: '
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Complete all of the following.
      options:
        - label: I've read the [Contributing Guidelines](https://github.com/cds-snc/gcds-components/blob/main/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/cds-snc/gcds-components/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I've searched for [existing issues](https://github.com/cds-snc/gcds-components/issues) that already report this problem, without success.
          required: true
  - type: textarea
    attributes:
      label: Describe the feature request.
      description: A clear and concise description of what the proposed new feature does that's distinct from existing gcds-components.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the use case.
      description: A clear and concise use case for what problem this feature would solve for most Government of Canada services or products.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the preferred solution.
      description: A clear and concise description of how you want this feature to be added to gcds-components.
  - type: textarea
    attributes:
      label: Describe all alternatives.
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    attributes:
      label: Provide related code or examples.
      description: Provide some sample code and/or screenshots to illustrate the feature request with examples.
  - type: textarea
    attributes:
      label: Add other relevant resources.
      description: Include any other information relevant to your request, like stack traces, related issues, suggestions how to implement, Stack Overflow links, forum links, etc.
