name: Build components
on:
  workflow_dispatch:
  pull_request:
      branches:
        - main
        - gcds-components-ssr

jobs:
  build-packages:
    name: Build all packages
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5
        with:
          node-version: 18

      - name: Install repo
        run: npm install

      - name: Build gcds-components
        run: npm run build

  build-storybook:
    name: Build storybook
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm install

      - name: Build gcds-components
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook
