name: Build components
on:
  workflow_dispatch:
  pull_request:
      branches:
        - main
        - gcds-components-ssr

jobs:
  build-packages:
    name: Build all packages
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18

      - name: Install repo
        run: npm install

      - name: Build gcds-components
        run: npm run build

  build-storybook:
    name: Build storybook
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm ci

      - name: Build gcds-components
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook
