name: Compile Core

jobs:
  build-deploy:
    name: Compile Core
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install repo
        run: npm install
      - name: FA dependency
        run: |
          npm i @fortawesome/fontawesome-free
          mv ./node_modules/@fortawesome ./packages/web/node_modules
      - name: Compile sass
        run: gulp compile
      - name: Run tests
        run: npm run test
      - name: Compile components
        run: npm run build
      - uses: JS-DevTools/npm-publish@c196e53609e852c243616a87994e8961a9903ba4
        with:
          token: ${{ secrets.NPM_TOKEN }}
