name: Publish packages
on: 
  push:
    branches:
      - main
    paths:
      - 'lerna.json'

jobs:
  build-deploy:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-node@5b32c9063c6eb277dacbf3e916a8bc5d2617c5b7
        with:
          node-version: 16.13.0
      - name: Install repo
        run: npm install
      - name: Install @cdssnc/gcds-components
        run: npm install
        working-directory: ./packages/web
      - name: Build @cdssnc/gcds-components
        run: npm run build
        working-directory: ./packages/web
      - uses: JS-DevTools/npm-publish@c196e53609e852c243616a87994e8961a9903ba4
        with:
          token: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/web
      - name: Install @cdssnc/gcds-components-react
        run: npm install
        working-directory: ./packages/react
      - name: Build @cdssnc/gcds-components-react
        run: npm run build
        working-directory: ./packages/react
      - uses: JS-DevTools/npm-publish@c196e53609e852c243616a87994e8961a9903ba4
        with:
          token: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/react
      - name: Install @cdssnc/gcds-components-angular
        run: npm install
        working-directory: ./packages/angular
      - name: Build @cdssnc/gcds-components-angular
        run: npm run build
        working-directory: ./packages/angular
      - uses: JS-DevTools/npm-publish@c196e53609e852c243616a87994e8961a9903ba4
        with:
          token: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/angular/dist
