name: Publish storybook
on: 
  push:
    branches:
      - main
    paths:
      - 'packages/web/src/**'
      - 'packages/web/.storybook/**'

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build-deploy:
    name: Publish storybook
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-node@d98fa1113850e562f83c7fc3a89c0ecd7a87fbed
        with:
          node-version: 16.13.0
      - name: Install repo
        run: npm install
      - name: Install gcds-components
        run: npm install
        working-directory: ./packages/web
      - name: Build gcds-components
        run: npm run build
        working-directory: ./packages/web
      - name: Build storybook
        run: npm run build-storybook
        working-directory: ./packages/web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: storybook
