name: Publish storybook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/web/src/**'
      - 'packages/web/.storybook/**'

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build-deploy:
    name: Publish storybook
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm install
        working-directory: ./packages/web

      - name: Build gcds-components
        run: npm run build
        working-directory: ./packages/web

      - name: Build storybook
        run: npm run build-storybook
        working-directory: ./packages/web
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: storybook
          keep_files: true
