name: Release Generator
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
        id: sre_app_token
        with:
          app-id: ${{ secrets.SRE_APP_ID }}
          private-key: ${{ secrets.SRE_APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        id: release
        with:
          token: ${{ steps.sre_app_token.outputs.token }}
