name: Release Generator
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@e995b4e40ace2eb5bf13137d9abe242c98f3aab6 # v1.6.0
        id: sre_app_token
        with:
          app_id: ${{ secrets.SRE_APP_ID }}
          private_key: ${{ secrets.SRE_APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v4
        with:
          command: manifest
          token: ${{ steps.sre_app_token.outputs.token }}
          release-type: node
          default-branch: main
