name: Renovate pull request
on: 
  pull_request:
      branches:
        - develop
      types:
        - labeled
        - opened
        - synchronize
        - reopened

jobs:
  build-packages:
    name: Build all packages
    if: contains(github.event.pull_request.labels.*.name, 'Renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        
      - uses: actions/setup-node@a9893b0cfb0821c9c7b5fec28a6a2e6cdd5e20a4
        with:
          node-version: 18

      - name: Install repo
        run: npm install

      - name: Install gcds-components
        run: npm install
        working-directory: ./packages/web

      - name: Build gcds-components
        run: npm run build
        working-directory: ./packages/web

      - name: Gcds-components link
        run: npm link
        working-directory: ./packages/web

      - name: Install gcds-components-react
        run: npm install
        working-directory: ./packages/react

      - name: Link @cdssnc/gcds-components
        run: npm link @cdssnc/gcds-components
        working-directory: ./packages/react

      - name: Build gcds-components-react
        run: npm run build
        working-directory: ./packages/react

      - name: Install gcds-components-angular
        run: npm install
        working-directory: ./packages/angular

      - name: Link @cdssnc/gcds-components
        run: npm link @cdssnc/gcds-components
        working-directory: ./packages/angular

      - name: Build gcds-components-angular
        run: npm run build
        working-directory: ./packages/angular

  build-storybook:
    name: Build storybook
    if: contains(github.event.pull_request.labels.*.name, 'Renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        
      - uses: actions/setup-node@a9893b0cfb0821c9c7b5fec28a6a2e6cdd5e20a4
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm install
        working-directory: ./packages/web

      - name: Build gcds-components
        run: npm run build
        working-directory: ./packages/web

      - name: Build Storybook
        run: npm run storybook
        working-directory: ./packages/web
