name: Run Tests
on: 
  pull_request:
      - main

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Compile sass
        run: gulp compile
      - name: Compile components
        run: npm run test
