name: Run Tests
on: 
  pull_request:
      branches:
        - main
        - develop

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm install
        working-directory: ./packages/web

      - name: Run tests
        run: npm run test
