name: Run Tests
on:
  pull_request:
      branches:
        - main

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build repo
        run: npm run build

      - name: Run tests
        run: npm run test
