name: Run Tests
on: 
  pull_request:
      branches:
        - main

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-node@d98fa1113850e562f83c7fc3a89c0ecd7a87fbed
        with:
          node-version: 16.13.0
      - name: Install gcds-components
        run: npm install
        working-directory: ./packages/web
      - name: Run tests
        run: npm run test
