name: Run Tests
on: 
  pull_request:
      branches:
        - main
  push:
    branches:
      - main
    paths:
      - 'styles/**'

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Install repo
        run: npm install
      - name: FA dependency
        run: |
          npm i @fortawesome/fontawesome-free
          mv ./node_modules/@fortawesome ./packages/web/node_modules
      - name: Compile sass
        run: gulp compile
      - name: Run tests
        run: npm run test
