name: Run Tests
on: 
  pull_request:
      branches:
        - main
  push:
    branches:
      - main
    paths:
      - 'styles/**'

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Install
        run: npm install
      - name: Compile sass
        run: gulp compile
      - name: Run tests
        run: npm run test
