name: Run Tests
on:
  pull_request:
      branches:
        - main

jobs:
  build-deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b
        with:
          node-version: 18

      - name: Install gcds-components
        run: npm install

      - name: Run tests
        run: npm run test
