name: Upload packages to CDN

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish packages"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  # TODO: Replace with correct bucket name in production
  CDN_BUCKET: gc-design-system-daine-scratch-cdn
  CDN_REGION: ca-central-1

jobs:
  upload-to-cdn:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "web"
            package: "@cdssnc/gcds-components"
            dist: "./packages/web"

          - name: "react"
            package: "@cdssnc/gcds-components-react"
            dist: "./packages/react"

          - name: "angular"
            package: "@cdssnc/gcds-components-angular"
            dist: "./packages/angular/dist"

          - name: "vue"
            package: "@cdssnc/gcds-components-vue"
            dist: "./packages/vue"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update ubuntu to get latest updates
        run: sudo apt-get update

      - name: Install jq to get lerna version from lerna.json
        run: sudo apt-get install -y jq

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Make retry script executable
        run: chmod +x ./utils/scripts/retry.sh

      - name: Make upload script executable
        run: chmod +x ./utils/scripts/upload_to_cdn.sh

      - name: Configure AWS credentials using OIDC
        # TODO: Replace with correct role on production
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3.0.2
        with:
          role-to-assume: arn:aws:iam::951846448183:role/daine-gcds-components-apply
          role-session-name: CDNPublish
          aws-region: ${{ env.CDN_REGION }}

      - name: Upload file to S3
        run: ./utils/scripts/upload_to_cdn.sh ${{ matrix.package }}
        env:
          CDN_BUCKET: ${{ env.CDN_BUCKET }}
          CDN_CLOUDFRONT_DIST_ID: ${{secrets.CDN_CLOUDFRONT_DIST_ID}}
          PACKAGE_PATH: ${{ matrix.dist }}

      - name: Slack notify on failure
        if: failure()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: CDN upload ${{ matrix.name }} failed: <https://github.com/cds-snc/gcds-components/actions/workflows/upload-cdn.yml|Upload packages to CDN>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_OPS }}
